'use client';

import { useState } from 'react';
import type { Analysis } from '../lib/api';

interface DownloadReportProps {
  analysis: Analysis;
  fileName: string;
}

export default function DownloadReport({ analysis, fileName }: DownloadReportProps) {
  const [generating, setGenerating] = useState(false);

  const generatePDF = async () => {
    setGenerating(true);
    try {
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();
      let y = 20;

      // Header
      doc.setFillColor(232, 93, 38);
      doc.rect(0, 0, 210, 30, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(20);
      doc.setFont('helvetica', 'bold');
      doc.text('NyayaAI', 14, 18);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('Legal Document Analysis Report', 14, 25);

      y = 40;
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(11);
      doc.setFont('helvetica', 'bold');
      doc.text(`Document: ${fileName}`, 14, y);
      y += 6;
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated: ${new Date().toLocaleDateString('en-IN')} | Risk Level: ${analysis.overallRisk.toUpperCase()}`, 14, y);

      y += 12;
      doc.setDrawColor(220, 220, 220);
      doc.line(14, y, 196, y);
      y += 8;

      // Summary
      doc.setTextColor(30, 30, 30);
      doc.setFontSize(13);
      doc.setFont('helvetica', 'bold');
      doc.text('Summary', 14, y);
      y += 7;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      const summaryLines = doc.splitTextToSize(analysis.summary, 180);
      doc.text(summaryLines, 14, y);
      y += summaryLines.length * 5 + 10;

      // Red flags
      if (analysis.redFlags && analysis.redFlags.length > 0) {
        doc.setFontSize(13);
        doc.setFont('helvetica', 'bold');
        doc.text('Red Flags', 14, y);
        y += 8;

        analysis.redFlags.forEach((flag) => {
          if (y > 260) { doc.addPage(); y = 20; }
          const riskColor = flag.risk === 'high' ? [220, 38, 38] : flag.risk === 'medium' ? [217, 119, 6] : [37, 99, 235];
          doc.setFillColor(riskColor[0], riskColor[1], riskColor[2]);
          doc.circle(16, y - 1, 1.5, 'F');

          doc.setFontSize(10);
          doc.setFont('helvetica', 'bold');
          doc.setTextColor(30, 30, 30);
          doc.text(`${flag.clause} [${flag.risk.toUpperCase()}]`, 20, y);
          y += 5;

          doc.setFontSize(9);
          doc.setFont('helvetica', 'normal');
          doc.setTextColor(80, 80, 80);
          const explLines = doc.splitTextToSize(flag.explanation, 170);
          doc.text(explLines, 20, y);
          y += explLines.length * 4.5 + 6;
        });
      }

      // Footer
      const pageCount = doc.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by NyayaAI · nyayaai.in · For guidance only, consult a licensed lawyer', 14, 290);
      }

      doc.save(`NyayaAI_Report_${fileName.replace(/\.[^/.]+$/, '')}.pdf`);
    } catch (err) {
      console.error('PDF generation failed:', err);
    } finally {
      setGenerating(false);
    }
  };

  return (
    <button onClick={generatePDF} disabled={generating} style={{ display: 'flex', alignItems: 'center', gap: 6, background: 'var(--bg-secondary)', border: '1px solid var(--border)', borderRadius: 9, padding: '7px 14px', fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', cursor: generating ? 'not-allowed' : 'pointer', opacity: generating ? 0.6 : 1 }}>
      <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
      {generating ? 'Generating...' : 'Download PDF'}
    </button>
  );
}
